fragment PurchaseHistory on PurchaseHistory {
  productsIds
  soldsIds
  quantityTotal
  priceTotal
  discountTotal
  percentageDiscount
  date
}

fragment User on User {
  id
  email
  username
  accessToken
  refreshToken
  roles

  purchaseHistory {
    ...PurchaseHistory
  }

  createdAt
  updatedAt
}

fragment ProductInUserBasket on ProductInUserBasket {
  productId
  price
  quantity
  title
  description
  image

  distinction {
    ...Distinction
  }

  sale {
    ...Sale
  }

  ratings {
    ...RatingsForGuest
  }

  views
  solds

  quantityTotal
  discountTotal
  priceTotal
}

fragment UserBasket on UserBasket {
  products {
    ...ProductInUserBasket
  }
  quantityTotal
  priceTotal
  discountTotal
  percentageDiscount
}
