query GetUser {
  getUser {
    ...User
  }
}

query Profile {
  profile {
    ...DecodedUser
  }
}

query GetBasket {
  getBasket {
    ...UserBasket
  }
}

query GetPurchaseHistory {
  getUser {
    purchaseHistory {
      ...PurchaseHistory
    }
  }
}
